name: video_player_with_controls
description: This package is prepared with the mindset of controlling the video player with easy to use controls. Simple controls have been added over the video player for easy access and manipulation of videos.
version: 0.0.2
homepage: https://github.com/Trend74X/Video-Player-With-Controls/blob/master/README.md
repository: https://github.com/Trend74X/Video-Player-With-Controls/tree/master

environment:
  sdk: '>=2.19.4 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
